### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Moi0** [GoogleChrome/private-tokens#13]
### Issuer Name

New user

### Origin

Https://www.xfinity.coc

### Contact Email

Chelbiowre@outlook.com

### Key Commitment Endpoint URL

Https://www.alexainternet.com

### Purpose

Trust issues.

### Disclosure and Acknowledgement

1. I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
2. I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
3. I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.
Yep.

**Comment by dvorak42** [comment]
Thank you for your submission. However it appears that this doesn't conform to our submission protocol in the following ways:

1) The origin name is invalid.
2) The key commitment endpoint URL does not provide valid key commitments.
3) The issuer name does not reflect the issuer origin.

If you intend to register as an issuer for Private State Tokens, please resubmit with a corrected issuer request. If you are having trouble with the issuer request, please post your question and we'll do our best to help.

**Comment by Moi0** [comment]
Yes. Huston is a problem.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Chelbi Breeden ***@***.***>
Sent: Wednesday, October 11, 2023 7:58:24 PM
To: GoogleChrome/private-tokens ***@***.***>
Cc: Chelbi Breeden ***@***.***>; Your activity ***@***.***>
Subject: [GoogleChrome/private-tokens] Token (Issue #13)


Issuer Name

New user

Origin

Https://www.xfinity.coc<https://www.xfinity.coc/>

Contact Email

***@***.******@***.***>

Key Commitment Endpoint URL

Https://www.alexainternet.com<https://www.alexainternet.com/>

Purpose

Trust issues.

Disclosure and Acknowledgement

  1.  I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
  2.  I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
  3.  I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.
Yep.
