### ISSUE TITLE
Private State Token Issuer Request - CaptchaFox

### ISSUE THREAD

**Issue by tgrassl** [GoogleChrome/private-tokens#16]
### Issuer Name

CaptchaFox Issuer

### Origin

https://issuer.captchafox.com

### Contact Email

support@captchafox.com

### Key Commitment Endpoint URL

https://issuer.captchafox.com/pst/key-commitment

### Purpose

To detect bots using trust signals

### Disclosure and Acknowledgement

1. I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
2. I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
3. I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.

**Comment by dvorak42** [comment]
The configuration and endpoint look good, I've filed a PR to add the configuration, however it may not be merged until after the weekend/holidays.

**Comment by dvorak42** [comment]
Your keys have been successfully parsed, they should be available in Chrome via component updater in approximately 4 hours.
