### ISSUE TITLE
Private State Token Issuer Request - AUTHFY

### ISSUE THREAD

**Issue by m4n3dw0lf** [GoogleChrome/private-tokens#18]
### Issuer Name

AUTHFY

### Origin

https://pst.authfy.tech

### Contact Email

webmaster@authfy.tech

### Key Commitment Endpoint URL

https://pst.authfy.tech/.well-known/trust-token/key-commitment

### Purpose

Authfy is an Anti-Fraud product developed by SEC4YOU (https://www.sec4u.com.br), we want to deliver to our clients the capability to use PST technology in order to prevent fraud and improve customer experience.

### Disclosure and Acknowledgement

1. I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
2. I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
3. I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.

**Comment by dvorak42** [comment]
It appears your expriy format is incorrect, you should have the expiry as a JSON string, rather than a number.

**Comment by m4n3dw0lf** [comment]
We've fixed the format for the expiry entry, i should close this issue and open a new one?

**Comment by dvorak42** [comment]
(Just updating this issue as you make fixes is fine, you don't need to open a new issue)

It looks like you're adding a "charset" parameter as part of the Content-Type for the key commitment, which is only valid for "text/" content types.

If its difficult to remove the charset parameter, we can see about removing that enforcement for the parser, but we won't likely be able to do that until the new year, if you can remove it from the content type on the endpoint, that might be the fastest way to resolve.

**Comment by m4n3dw0lf** [comment]
you mean the: `; charset=utf-8`, don't worry, you can keep the enforcement we will manage to remove this guy from the header, i'll let you known when its done.

**Comment by m4n3dw0lf** [comment]
@dvorak42, done i've tested with `curl -v` and the `; charset=utf-8` is gone. let me know if anything else is missing or need to be adjusted.

**Comment by dvorak42** [comment]
Sorry, missed checking it the first time. It looks like your "id" and "batchsize" fields are currently strings, while they should be integers (you'll need to get rid of the quotes for those two fields in the top-level dictionary).

**Comment by m4n3dw0lf** [comment]
But the spec on the URL https://wicg.github.io/trust-token-api/ states that:

"batchsize" specifies the maximum number of masked tokens that the issuer supports for each token issuance operation. Its value is a **string representation** of a positive integer. 

"id" field provides the identifier of the key commitment. It is a **string representation** of a non-negative integer that is within the range of an unsigned 32 bit integer type. Values should be montonically increasing.

Apologies in advance if my understanding was wrong.

**Comment by dvorak42** [comment]
Unfortunately I believe this is a bug that cropped up when we converted the design document/explainer into a spec document.

The correct behavior is that those two fields should be integers, I've filed https://github.com/WICG/trust-token-api/issues/279 to track fixing the spec issue.

**Comment by m4n3dw0lf** [comment]
Thanks, i checked the PR https://github.com/WICG/trust-token-api/pull/280 opened by aykutbulut, with the fix of the 2 fields definition, we're proceeding with the change to integer, i let you know when its done.

**Comment by m4n3dw0lf** [comment]
@dvorak42 the server has been updated with the fix, let me know if anything else is missing.

**Comment by dvorak42** [comment]
Hi, everything looks good. However with the holidays, the PR (#19) to merge in your issuer may not get reviewed and imported until Tuesday.

**Comment by m4n3dw0lf** [comment]
No problem, thanks @dvorak42 feel free to reach out for anything else.

**Comment by dvorak42** [comment]
Your keys have been successfully parsed, they should be available in Chrome via component updater in approximately 4 hours  (you can force an update by going to chrome://components/ and hitting "Check for update" under Trust Token Key Commitments).
