### ISSUE TITLE
New PST Issuer

### ISSUE THREAD

**Issue by Malashkin** [GoogleChrome/private-tokens#25]
"https://mercury-ambitious-muenster.glitch.me": {
		"name": "Fraud test",
		"contact": "xb-dx@yandex.ru",
		"endpoint": "https://mercury-ambitious-muenster.glitch.me/.well-known/trust-token/key-commitments",
		"expiry": "1719633600"
	},

**Comment by dvorak42** [comment]
Please follow the process described in https://github.com/GoogleChrome/private-tokens/blob/main/PST-Registration.md for registering as a new issuer.
