### ISSUE TITLE
Private State Token issuer re-register - Amazon ads issuer

### ISSUE THREAD

**Issue by hardikbkk** [GoogleChrome/private-tokens#28]
[re-registering issuer as the current registration will expire on 24th Sep 2024]

Summary: Private State Token Issuer Request - Amazon Ads issuer
Description: Amazon Ads issuer to detect invalid traffic
Issuer Name : Amazon Ads issuer
Origin : https://www.amazon.com/
Contact: amazon-ads-pst-issuer@amazon.com
Key Commitment Endpoint URL: https://www.amazon.com/tt/k
Purpose: Invalid traffic detection

Disclosure & Acknowledgement:

I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.

**Comment by hardikbkk** [comment]
[pst-issuer](https://github.com/GoogleChrome/private-tokens/labels/pst-issuer)

**Comment by dvorak42** [comment]
Updated the expiration for the keys.
