### ISSUE TITLE
New PST Issuer

### ISSUE THREAD

**Issue by maceip** [GoogleChrome/private-tokens#6]
### Issuer Name

Polyset Issuer

### Origin

https://polyset.xyz

### Contact Email

id@polyset.xyz

### Key Commitment Endpoint URL

https://polyset.xyz/pst/keys

### Purpose

a public good identity provider offering federated credential management and private state tokens for all

### Disclosure and Acknowledgement

1. I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
2. I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
3. I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.

**Comment by dvorak42** [comment]
The endpoint does not seem to be serving any keys. Connections to it seem to be stuck loading.

**Comment by maceip** [comment]
should be functional now!

**Comment by dvorak42** [comment]
The keys seem to be okay, however the endpoint should be returning an "application/pst-issuer-directory" content-type/media-type on the key commitments (https://github.com/WICG/trust-token-api/blob/main/spec.bs#L183) to confirm that they're intended to be interpreted as key commitments.

Let me know when you've updated the endpoint and we can rerun the configuration.

**Comment by maceip** [comment]
The media-type has been updated 🧼

**Comment by dvorak42** [comment]
It looks like you're adding a "charset" parameter as part of the Content-Type, which is only valid for "text/" content types.

I'll raise whether ignoring the "charset" parameter is okay for this Content-Type, but if you can remove it from the content type on the endpoint, that might be the fastest way to resolve.

**Comment by maceip** [comment]
removed charset :shipit:

**Comment by dvorak42** [comment]
Your keys have been successfully parsed, they should now be available in Chrome via component updater (you can force an update if you have an up-to-date M114 with the feature enabled by going to chrome://components/ and hitting "Check for update" under Trust Token Key Commitments).
